
import { Product, Category } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    title: 'آیفون ۱۳ پرو مکس ۲۵۶ گیگ',
    price: 'توافقی',
    location: 'تهران، سعادت‌آباد',
    time: 'دقایقی پیش',
    category: Category.ELECTRONICS,
    imageUrl: 'https://picsum.photos/id/10/400/300',
  },
  {
    id: 2,
    title: 'مبل راحتی ۷ نفره چرم',
    price: '۵,۵۰۰,۰۰۰ تومان',
    location: 'کرج، گوهردشت',
    time: '۱ ساعت پیش',
    category: Category.HOME,
    imageUrl: 'https://picsum.photos/id/20/400/300',
  },
  {
    id: 3,
    title: 'پژو ۲۰۶ تیپ ۵ مدل ۹۹',
    price: '۴۵۰,۰۰۰,۰۰۰ تومان',
    location: 'اصفهان، شاهین‌شهر',
    time: '۳ ساعت پیش',
    category: Category.VEHICLES,
    imageUrl: 'https://picsum.photos/id/30/400/300',
  },
  {
    id: 4,
    title: 'ساعت هوشمند اپل واچ سری ۷',
    price: '۸,۰۰۰,۰۰۰ تومان',
    location: 'شیراز، معالی‌آباد',
    time: '۵ ساعت پیش',
    category: Category.PERSONAL,
    imageUrl: 'https://picsum.photos/id/40/400/300',
  },
  {
    id: 5,
    title: 'آپارتمان ۱۲۰ متری، ۲ خوابه',
    price: 'ودیعه: ۵۰۰ میلیون، اجاره: ۱۰ میلیون',
    location: 'تهران، پونک',
    time: 'دیروز',
    category: Category.REAL_ESTATE,
    imageUrl: 'https://picsum.photos/id/50/400/300',
  },
  {
    id: 6,
    title: 'لپتاپ مک‌بوک ایر M1',
    price: '۲۸,۰۰۰,۰۰۰ تومان',
    location: 'مشهد، وکیل‌آباد',
    time: 'دیروز',
    category: Category.ELECTRONICS,
    imageUrl: 'https://picsum.photos/id/60/400/300',
  },
  {
    id: 7,
    title: 'یخچال ساید بای ساید سامسونگ',
    price: '۴۰,۰۰۰,۰۰۰ تومان',
    location: 'تهران، نیاوران',
    time: '۲ روز پیش',
    category: Category.HOME,
    imageUrl: 'https://picsum.photos/id/70/400/300',
  },
  {
    id: 8,
    title: 'پراید ۱۳۱ مدل ۹۸',
    price: '۲۱۰,۰۰۰,۰۰۰ تومان',
    location: 'تبریز، ولیعصر',
    time: '۳ روز پیش',
    category: Category.VEHICLES,
    imageUrl: 'https://picsum.photos/id/80/400/300',
  },
   {
    id: 9,
    title: 'دوربین عکاسی کانن 80D',
    price: '۲۰,۰۰۰,۰۰۰ تومان',
    location: 'تهران، انقلاب',
    time: 'هفته پیش',
    category: Category.ELECTRONICS,
    imageUrl: 'https://picsum.photos/id/90/400/300',
  },
  {
    id: 10,
    title: 'فرش دستبافت کاشان ۶ متری',
    price: '۱۲,۰۰۰,۰۰۰ تومان',
    location: 'کاشان',
    time: 'هفته پیش',
    category: Category.HOME,
    imageUrl: 'https://picsum.photos/id/100/400/300',
  },
];

export const CATEGORIES = Object.values(Category);
